### ISSUE TITLE
Commit 61df0e2f5e90 introduced a requirement for asgiref 3.6.0+

### ISSUE THREAD

**Issue by vainu-arto** [jazzband/django-simple-history#1255]
In commit 61df0e2f5e90 the middleware started using function `iscoroutinefunction` from `asgiref.sync`. This function is introduced in version 3.6.0.

It seems that this commit also introduced a hard dependency on asgiref which previously didn't exist (the use in models.py is conditional).

The easy fix is to add a versioned requirement for asgiref.

**Comment by ddabble** [comment]
As far as I've understood, we only use `asgiref` because it's what Django itself uses and [recommends using for async middleware](https://docs.djangoproject.com/en/4.2/topics/http/middleware/#asynchronous-support), and so we will only ever have the need to use [the exact same version as Django requires](https://github.com/django/django/blob/4.2.5/setup.cfg#L42). In other words, if Django changed its required `asgiref` version or stopped using it altogether, we would most likely (have to) follow suit.

Because of this, I'm not entirely sure why not adding `asgiref` to our requirements could be a problem; would you mind explaining? 🙂

**Comment by vainu-arto** [comment]
Not all supported versions of Django require asgiref 3.6.0. As an obvious example, Django 3.2 requires asgiref 3.3.2: https://github.com/django/django/blob/3.2.21/setup.cfg#L45

The problem could also be solved by directly requiring Django 4.2, but that doesn't sound right to me.

**Comment by ddabble** [comment]
Ah, I missed your point above that `iscoroutinefunction()` was introduced in `asgiref` 3.6.0.

I can see from [the CI test logs for the commit you mentioned](https://github.com/jazzband/django-simple-history/actions/runs/5771434034/job/15645382998) that `asgiref==3.7.2` was actually installed for all Django versions (which I'm guessing is because that version is cached, which `pip` seems to prefer), which explains why the tests didn't fail.

**Comment by ddabble** [comment]
I opened #1261 to implement the versioned requirement you mentioned initially.
