### ISSUE TITLE
[Question] How to prevent history from being created for a new object? Also how to set user to history after it has been created?

### ISSUE THREAD

**Issue by marcio0** [jazzband/django-simple-history#1315]
Hi, I have a few async tasks running on Celery where data is created, and I'm having a couple issues:

1. Some objects are first created with get_or_create or update_or_create, and later more data is added and the object is saved again, causing it to have two history entries. Is there a way to prevent the first history from being created? I only saw a solution to do it when the object already exists, by setting `skip_history_when_saving`.

2. I also need to manually set the user to the history since there's no request happening. Is there something like `update_change_reason` for setting the user, or a way to inform what is the user for the next histories created, like a context manager? The only way I found was retrieving the history from the db, setting the user, and saving it again.

**Comment by ddabble** [comment]
1. That's unfortunately not possible, other than by changing the `SIMPLE_HISTORY_ENABLED` setting (see [the docs on saving without a historical record](https://django-simple-history.readthedocs.io/en/latest/querying_history.html#save-without-a-historical-record) and [the source code](https://github.com/jazzband/django-simple-history/blob/3.5.0/simple_history/models.py#L633-L639)).
  Though I'm curious whether you could redesign your code to circumvent this.. Because it should be possible to replace both `get_or_create()` and `update_or_create()` with a `get()` followed by adding the data you mentioned and saving - unless you have a specific reason to use those methods..? 🤔

2. I think [the docs on user tracking](https://django-simple-history.readthedocs.io/en/latest/user_tracking.html) should cover this 🙂

**Comment by marcio0** [comment]
Good point about separating get_or_create, I can fetch it, or create a new instance, using `skip_history_when_saving` and then saving it. I overlooked that solution.

That would fix it for the second issue as well, as I can set `_history_user` on the newly created object before saving it.

Thanks!
