### ISSUE TITLE
Add support for as_of_related on HistoryManager

### ISSUE THREAD

**Issue by treyhunner** [jazzband/django-simple-history#17]
As implemented in this fork: https://bitbucket.org/joaofrancese/django-simple-history/src/0d1630812d2e/simple_history/manager.py?at=default

**Comment by jlachowski** [comment]
Any news on this? Will it be incorporated?

**Comment by macro1** [comment]
Hi @jlachowski. As you can see, this issue was opened a very long time ago, and both @treyhunner and I have no need for it. There has been some discussion in #118 for a similar feature, and I can't think of any good technical reasons it couldn't be added.

Unfortunately I don't have the time to take point on adding this feature, and I don't have a need for it, so I wouldn't be able to exercise it in a real project. If you, or someone else in the #118 discussion has interest, I would be happy to help with getting the feature into django-simple-history.

**Comment by jeking3** [comment]
I am going to close this issue in favor of #118.  The original branch is not accessible any more.
