### ISSUE TITLE
Add new version/record without updating main model

### ISSUE THREAD

**Issue by FelixHenninger** [jazzband/django-simple-history#705]
**Thank you all for your work on this awesome library!** I have a feature request that came up in one of my projects recently, and might already be implemented, or might be out of scope entirely. Either way, I'd be super-glad to hear your thoughts.

The **background** is that I already use (and love!) django-simple-history for retrospective versioning, and I've been wondering whether it would be possible to build a very basic moderation-type system on top of it by pinning a model to a particular version that is not necessarily the last one.
A good **example** for this would be [Wikipedia's pending pages protection](https://en.wikipedia.org/wiki/Wikipedia:Pending_changes) that keep the visible content at one particular version, but continue accepting edits that need to be reviewed by an admin/editor before that version becomes visible by default, and replaces the previous content.

----

**Problem Statement**
I'd like to add to the historical record of a model without changing the main version of the model, and later update the model independently to a record in the 'history'.

**Describe the solution you'd like**
I'd like to implement a workflow in which changes create _only_ a new version without updating the original model.

**Describe alternatives you've considered**
I've seen that you provide an example for the inverse, which is [updating the current model without creating history](https://django-simple-history.readthedocs.io/en/latest/querying_history.html#save-without-a-historical-record). Maybe what I'm asking for would be possible (in a hackish way) by saving the model and immediately reverting to a certain version?

Another alternative would be using a moderation library such as [django-moderation](https://github.com/dominno/django-moderation), but I'd much rather do versioning in a single workflow. Also, django-moderation assumes that a model is visible or not, and (as far as I can tell) doesn't deal well with changes to an existing model.

----

Ok, so much -- any thoughts and ideas would be super-appreciated; if this is in scope, I'd be happy to contribute code to make it possible.

Kind regards, and many thanks, -Felix

**Comment by rossmechanic** [comment]
Hey @FelixHenninger, glad you enjoy the library! You can actually access the historical models directly and create records in them. If I have the below `myapp/models.py` file:

```
class MyModel(models.Model):
    ...
    history = HistoricalRecords()
```

I can access the historical model by importing it directly:
```
from myapp.models import HistoricalMyModel
```

or by accessing it through the base model:
```
from simple_history.utils import get_history_model_for_model
from myapp.models import MyModel

HistoricalMyModel = get_history_model_for_model(MyModel)
```

**Comment by khashashin** [comment]
Exactly what I looking for. Just wanted to create an issue and ask about it and saw your Issue. Some method like `save_in_history()`  which creates the record avoiding any changes in main data of the model then after some trigger(`status`, `pending_changes` etc.) it could apply this changes to main model and in the same time create history record.

**Comment by khashashin** [comment]
Please, could someone who has more experience with django-simple-history agree with following solution:

Create BaseModel:

```
class BaseModel(models.Model):
    class PublishingStatus(models.TextChoices):
        DRAFT = 'draft', _('Draft')
        ACCEPTED = 'accepted', _('Accepted'),
        REJECTED = 'rejected', _('Rejected')

    publishing_status = models.CharField(
        max_length=9,
        choices=PublishingStatus.choices,
        default=PublishingStatus.DRAFT,
        help_text=_("Publishing status represents the state of the object. By default it is 'draft'")
    )

    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True
```

Each model that should have "Public" and "Intern" version should inherit from BaseModel:

```
class Blog(BaseModel):
    title = models.CharField(max_length=255, default="")
    body = models.TextField(default="")

class Product(BaseModel):
    title = models.CharField(max_length=255, default="")
    description = models.TextField(default="")
```

Create custom Manager for each model which returns an object from historymodel that has `publishing_status="accepted"`

```
class BlogManager(models.Manager):
    PublicBlog = get_history_model_for_model(Blog)

    def accepted(self) -> QuerySet:
        queryset = PublicBlog.get_queryset()
        return queryset.filter(publishing_status='accepted').last()

    def draft(self) -> QuerySet:
        queryset = self.get_queryset()
        return queryset.filter(publishing_status='draft')


class ProductManager(models.Manager):
    PublicProduct = get_history_model_for_model(Product)

    def accepted(self) -> QuerySet:
        queryset = PublicBlog.get_queryset()
        return queryset.filter(publishing_status='accepted').last()

    def draft(self) -> QuerySet:
        queryset = self.get_queryset()
        return queryset.filter(publishing_status='draft')
```

Update `Blog` and `Product` models to use this managers:

```
class Blog(BaseModel):
    title = models.CharField(max_length=255, default="")
    body = models.TextField(default="")

    objects = BlogManager()

class Product(BaseModel):
    title = models.CharField(max_length=255, default="")
    description = models.TextField(default="")

    objects = ProductManager()
```

I think, this solution will keep updating the model and you don't really need worry about the "main" model. You will get always the last version of accepted model and all other records will be also available.

I'd happy to hear about it from you guys, since I need this kind of solution in my current project.

**Comment by khashashin** [comment]
**Updates to my previous comment**

The model in Manager we can access using `self.model` inside `accepted` or `rejected` querysets and here is updates version of previous code:

    def accepted(self) -> QuerySet:
        versions = get_history_model_for_model(self.model)
        queryset = versions.objects.all()
        return queryset.filter(publishing_status='accepted').order_by('id').distinct('id')

Please note the `order_by` and `distinct` filters in returning queryset. We need handle somehow the duplicate data that we get from HistoryModels

![image](https://user-images.githubusercontent.com/17837758/94352278-21935c80-0063-11eb-85ea-c0f191ebf618.png)

It is simple if you use Postgres as your Database but you need to handle this duplicates somehow if you use another database.

One of the solution would be to use `post_save` signal get the data from historymodel by the id and change all `published_status` to `draft` excluding the last one.

**Comment by FelixHenninger** [comment]
Hi @khashashin, and thanks for sharing your thoughts, sound like we were working on the exact same functionality! My approach was pretty much in line with yours, and I also ran into the same issue with `distinct`. My (very hackish) workaround for local development looked like this:

```
from django.db import models, connection

# ...

class VersionQuerySet(models.QuerySet):
    def latest(self):
        if connection.vendor == 'postgresql':
            return self \
                .order_by('uuid', '-history_date') \
                .distinct('uuid')
        else:
            # This is a hack in order to simulate SQL's
            # DISTINCT ON in backends that don't support it.
            # It's necessarily less efficient than
            # the native implementation.
            latest_ids = self.order_by() \
                .values('uuid') \
                .annotate(max_id=models.Max('id')) \
                .values_list('max_id', flat=True)

            return self.filter(id__in=latest_ids)
```

Maybe that helps? I very much like your approach, and would for sure love to see a canonical implementation of this workflow! Kind regards,


-Felix

**Comment by khashashin** [comment]
@FelixHenninger I decided to refactor the approach described above because I encountered some difficulties in serializing my models in the DRF. My new solution is not clean, it adds a lot of code (depending on the amount of your models, of course, where you will keep the change history). Using the following query set is fine:

    def accepted(self) -> QuerySet:
        versions = get_history_model_for_model(self.model)
        queryset = versions.objects.all()
        return queryset.filter(publishing_status='accepted')

but this returns objects of the Hostory model and not the objects of the actual model from which you are performing the query. So this will cause problems if you plan to use DRF, because the serializers wait for the objects of the "real" model and not the history model. Also this object lose the relationship configuration between the models, since history model does not keep them.

Now I use the `post_save` signal and some tricks to deal with recursions. I give a clarification and explanation of the code below. You will do nothing until there is an entry of a certain instance in the history model with the record `publishing_status=accepted`, which means that you have not accepted any changes until now. It also makes no sense to do anything with a newly created entry in the database, so skip that one too. I also keep all new entries as `draft` by default (see my `BaseModel` in the comments above), so that I (or the moderators of the content) can accept the entry manually. This means to execute the following code only if the entry had `publishing_status=draft` during save method execution, in all other cases like `publishing_status=rejected`, `publishing_status=modified` or `publishing_status=accepted` do nothing:

@receiver(post_save, sender=Product)
def skip_changes_in_main_model_and_save_them_in_history(sender, instance=None, created=False, **kwargs):
    last_accepted_version = instance.history.filter(id=instance.id, publishing_status='accepted').last()
    if created:
        return
    if not instance.publishing_status == 'draft':
        return
    if not last_accepted_version:
        return
    post_save.disconnect(skip_changes_in_main_model_and_save_them_in_history, sender=Product)
    instance.skip_history_when_saving = True
    last_accepted_version.instance.save()
    del instance.skip_history_when_saving
    post_save.connect(skip_changes_in_main_model_and_save_them_in_history, sender=Product)

This method above basically does revert of the model that is described in the django_simple_history [documentation](https://django-simple-history.readthedocs.io/en/latest/querying_history.html#reverting-the-model) skipping the history since we know what we are doing at this point and will not add garbage to our history (skipping history currently does not work, I don't know why I've to look at this deeply)
