### ISSUE TITLE
Compatibility with Django 4.0?

### ISSUE THREAD

**Issue by pallavg** [jazzband/django-simple-history#940]
**Problem Statement**
I have used this excellent plugin before in Django 3.1/3.2. It works without any issues. However, when I tried running it on Django 4.0, I got some errors. Looks like there are some API changes in Django 4.0. For example, "The providing_args argument for django.dispatch.Signal is removed.". See https://docs.djangoproject.com/en/4.0/releases/4.0/. There might be others but since I'm not a library developer, I'm not sure.

**Describe the solution you'd like**
Please support this plugin on Django 4.0.

**Describe alternatives you've considered**
I don't have one as this plugin is excellent.

**Additional context**
None.

**Comment by SAbimhamed** [comment]
I am facing the following issue:
File "/Users/...../Library/Python/3.8/lib/python/site-packages/django/db/models/fields/__init__.py", line 1086, in decons
truct
    if self.db_collation:
AttributeError: 'CountryField' object has no attribute 'db_collation'

**Comment by jeking3** [comment]
@pallavg The CI tests are failing against django's main branch but they are passing against the 4.0 release.  That issue still needs to be resolved but otherwise we have no known issues with Django 4.0 at the moment.

@SAbimhamed `self.db_collation` is not present anywhere in this codebase.  The only place I could find is in models.py:transform_field where we set a field's db_collation attribute to None.  However, this does not align with what you reported.

**Comment by zahidmian** [comment]
@jeking3 I have the same issue (unexpected keyword argument 'providing_args') with Django 4.0. It's because [conda-forge package](https://anaconda.org/conda-forge/django-simple-history) is not updated with the latest version. Can this be updated?
