### ISSUE TITLE
Ability to Easily Query All Records Where `history_user_id=some_id`

### ISSUE THREAD

**Issue by justin-f-perez** [jazzband/django-simple-history#998]
**Problem Statement**

I would like to more easily determine the latest `history_date` among all `HistoryRecords` for a particular `history_user`.

I read through the docs, first 2 pages of issue titles on github, and searched issues before opening this... apologies if this is already a thing and I just missed it!

**Describe the solution you'd like**

A method for retrieving all `Historical<Model>` instances associated to a particular `history_user`. This could be a list of querysets (1 per history model), a single queryset (as long as there's some linkage back to the history model so we can determine what changed), etc.

**Describe alternatives you've considered**

I considered a [polymorphic](https://django-polymorphic.readthedocs.io/en/stable/) AbstractbaseHistoryModel. I *think* this would allow something like:
```python
from simple_history.models import HistoryBase
fired_username = "djtrump"  # just a friendly/cheeky jab; if anyone is offended I will change the example
qs = HistoryBase.objects.filter(history_user__username=fired_username)
```
And each instance of `qs` would be an instance of a concrete subclass of the base model. However, this would
1) Introduce a new dependency
2) May significantly alter existing database structure, and my gut feeling is that there's no safe way to do this without risking data loss (because not everyone reads patch notes)

**Additional context**
Recently, I had an issue in a production environment where a fired employee's access to a system was not properly terminated. I could tell from `user.last_login` that they'd logged in long after they'd been fired. It was up to me to determine whether or not they'd modified any system resource. Thankfully, we were using this excellent package to track changes made by users. However, it wasn't clear to me how to get *all* historical records associated to a particular `User`.

**Comment by justin-f-perez** [comment]
Some additional thoughts/experiments:

### "Maybe there's already a relation on User between the historical models?"

None that I could find (proprietary models replaced with "app.model")

```python
[ins] In [48]: User._meta.local_many_to_many
Out[48]:
[<django.db.models.fields.related.ManyToManyField: groups>,
 <django.db.models.fields.related.ManyToManyField: user_permissions>]

[ins] In [49]: User._meta.related_objects
Out[49]:
(<ManyToOneRel: admin.logentry>,
 <OneToOneRel: app.model>,
 <ManyToManyRel: app.model>,
 <ManyToOneRel: app.model>,
 <ManyToManyRel: app.model>,
 <ManyToManyRel: app.model>,
 <ManyToOneRel: app.model>,
 <ManyToOneRel: app.model>)

**Comment by ddabble** [comment]
If I've understood you correctly, querying the historical records for a particular field (`history_user` in your case) *is* mentioned in the docs - albeit slightly vaguely; see ["Querying history on a model class"](https://django-simple-history.readthedocs.io/en/latest/querying_history.html#querying-history-on-a-model-class), where you can also filter on fields like `history_user`.

As an example, for a model `Poll`, either of these calls should work:
```python
Poll.history.filter(history_user__username="admin").latest()
HistoricalPoll.objects.filter(history_user__username="admin").latest()
```

Lastly, regarding you not being able to find a relationship attribute on the `User` model to the historical model: This is because the default value passed to the `related_name` argument of the foreign key to `User`, is `"+"`, and so no reverse manager is created. This can be changed, however, using [the `user_related_name` argument of `HistoricalRecords`](https://github.com/jazzband/django-simple-history/blob/3.4.0/simple_history/models.py#L84).

**Comment by ddabble** [comment]
Closing, as the issue seems resolved. Please reopen if that's not the case 🙂
